work_dir: ./work_dir/d_gait/CTRGCN_Text_100epoch_ViT14_1.0_64_128_BoneMotion

# feeder
feeder: feeders.feeder_CTRGCN.Feeder
train_feeder_args:
  data_path: /root/DGait_CTRGCN/data/processed_data_train/d_gait_train.npz
  sample_path: /root/DGait_CTRGCN/data/denoised_data_train/dname.txt
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: False
  p_interval: [0.5, 1]
  vel: True
  bone: True

test_feeder_args:
  data_path: /root/DGait_CTRGCN/data/processed_data_test/d_gait_test.npz
  sample_path: /root/DGait_CTRGCN/data/denoised_data_test/dname.txt
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: True
  bone: True
  debug: False

# model
model: model.ctrgcn.Model_4part
model_args:
  num_class: 2
  num_point: 17
  num_person: 1
  graph: graph.d_gait_d.Graph
  head: ['ViT-L/14']
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 128
num_epoch: 100
nesterov: True
